apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: yb-demo
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000